version: "3.7"
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_USER: gameshub
      MYSQL_PASSWORD: clave123
      MYSQL_ROOT_PASSWORD: clave123
      MYSQL_DATABASE: gameshub
      TZ: America/Santiago
    volumes:
    - ./datadir:/var/lib/mysql