quarkus:
  http:
    cors:
      enable: true
      origins: '*'
      headers: accept, authorization, content-type, x-requested-with
      methods: GET,POST,PUT,DELETE,OPTIONS
    time-zone: America/Santiago
  datasource:
    db-kind: mysql
    username: gameshub
    password: clave123
    jdbc:
      driver: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/gameshub?autoReconnect=true
    #"dummy":
      #db-kind: h2
      #username: sa
      #password: password
      #jdbc:
        #driver: org.h2.Driver
        #url: jdbc:h2:mem:testdb
  hibernate-orm:
    database:
      generation: update
    #"dummy":
      #packages: io.quarkus.hibernate.orm.panache.common
      #datasource: dummy
  native:
    add-all-charsets: true
    container-build: false
  swagger-ui:
    path: /swagger-ui
  smallrye-openapi:
    path: /swagger
    info-title: MS-GAMESHUB-API
    info-description: GAMESHUB API